### ISSUE TITLE
Packaging for Arch Linux

### ISSUE THREAD

**Issue by radupotop** [tusharsadhwani/formatjson#3]
Hi, 

Just wanted to let you know that I found your rust package very useful and took the liberty to package it for Arch Linux.
You can find it here in the AUR: https://aur.archlinux.org/packages/formatjson

It would be great if you could add a `git tag` when you bump the version, so I can pull the exact release.

Thanks again,

Radu

**Comment by tusharsadhwani** [comment]
Sure, I'll start doing that.

**Comment by tusharsadhwani** [comment]
I pushed a new tag (0.2.1), LMK if it works out!

**Comment by radupotop** [comment]
That works well, thanks!

**Comment by tusharsadhwani** [comment]
@radupotop Can you package 0.3.1 as well? It improves the speed by a factor of a 100.

**Comment by radupotop** [comment]
Sure thing. Btw I don't get notified of new tags, but if you create a release in Github then your subscribers will be notified.

**Comment by tusharsadhwani** [comment]
Sure, I can do releases as well.
